plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
show_downloads: true
github:
  another_url: another value
include:
  - README.md
  - PULL_REQUEST_TEMPLATE.md
description: VisitContactTrace
theme: jekyll-theme-time-machine
markdown: kramdown
