plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
show_downloads: true
github:
  zip_url: https://github.com/vnsny-bia/VisitContactTrace/blob/master/readme-files/VisitContactTrace_0.1.0.tar.gz
  another_url: another value
include:
  - README.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-time-machine
